<?php
include_once 'Point.php';

class MovablePoint extends Point{
protected $xSpeed=0;
protected $ySpeed=0;

    /**
     * @return int
     */
    public function getXSpeed()
    {
        return $this->xSpeed;
    }

    /**
     * @return int
     */
    public function getYSpeed()
    {
        return $this->ySpeed;
    }

    /**
     * @param int $xSpeed
     */
    public function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @param int $ySpeed
     */
    public function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }
    public function setSpeed($xSpeed,$ySpeed){

    }
    public function getSpeed(){


    }
    public function __toString()
    {
        return parent::__toString().',speed=(xs,ys)'; // TODO: Change the autogenerated stub
    }
    public function __construct($x, $y, $xSpeed, $ySpeed){
        $this->x=$x;
        $this->y=$y;
        $this->xSpeed=$xSpeed;
        $this->ySpeed=$ySpeed;
    }

    public function move(){
        $this->__construct();
    }
}
