<?php
include_once 'Point2D.php';

class Point3D extends Point2D{
    protected $z=0;

    public function __construct($x, $y,$z)
    {
        parent::__construct($x, $y);
        $this->z=$z;
    }
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * @param int $z
     */
    public function setZ($z)
    {
        $this->z = $z;
    }
    public function setXYZ($x, $y,$z)
    {

    }
    public function getXYZ(){

    }
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}
{

}